// <auto-generated />
using System;
using EquipmentService.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentService.Infrastructure.Migrations
{
    [DbContext(typeof(EquipmentContext))]
    [Migration("20260924183455_RentalListingMigration")]
    partial class RentalListingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RentIt.Categories", (string)null);
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Equipments.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RentIt.Equipments", (string)null);
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Equipments.EquipmentImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentImage");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Listing.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RentalListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Listing.RentalListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaximumRentalDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumRentalDays")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RentIt.RentalListings", (string)null);
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Equipments.Equipment", b =>
                {
                    b.HasOne("EquipmentService.Core.Domain.Entities.Categories.Category", "Category")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Equipments.EquipmentImage", b =>
                {
                    b.HasOne("EquipmentService.Core.Domain.Entities.Equipments.Equipment", "Equipment")
                        .WithMany("Images")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Listing.ListingImage", b =>
                {
                    b.HasOne("EquipmentService.Core.Domain.Entities.Listing.RentalListing", "RentalListing")
                        .WithMany("Images")
                        .HasForeignKey("RentalListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalListing");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Listing.RentalListing", b =>
                {
                    b.HasOne("EquipmentService.Core.Domain.Entities.Equipments.Equipment", "Equipment")
                        .WithMany("Listings")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EquipmentService.Core.Domain.Entities.Shared.Currency", "PenaltyFeePerDay", b1 =>
                        {
                            b1.Property<Guid>("RentalListingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RentalListingId");

                            b1.ToTable("RentIt.RentalListings");

                            b1.WithOwner()
                                .HasForeignKey("RentalListingId");
                        });

                    b.OwnsOne("EquipmentService.Core.Domain.Entities.Shared.Currency", "PricePerDay", b1 =>
                        {
                            b1.Property<Guid>("RentalListingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RentalListingId");

                            b1.ToTable("RentIt.RentalListings");

                            b1.WithOwner()
                                .HasForeignKey("RentalListingId");
                        });

                    b.Navigation("Equipment");

                    b.Navigation("PenaltyFeePerDay")
                        .IsRequired();

                    b.Navigation("PricePerDay")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("EquipmentItems");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Equipments.Equipment", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("EquipmentService.Core.Domain.Entities.Listing.RentalListing", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
