<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentIT.UI.Core\RentIT.UI.Core.csproj" />
    <ProjectReference Include="..\RentIT.UI.Infrastructure\RentIT.UI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
